trigger: none

variables:
  - template: variables.yml

pool:
  vmImage: windows-latest

stages:
  - template: management_release.yml
    parameters:
      stage_name: DeployToDemo
      environment: Demo
      location: ${{ upper(variables.azure_region) }}
      company: ${{ upper(variables.company) }}
      serviceConn: ${{ variables.devServiceConn }}