trigger: none 

variables:
  - template: variables.yml

pool:
  vmImage: windows-latest

stages:
  - template: virtualMachine_release.yml
    parameters:
      stage_name: DeployToTraining
      environment: Training
      location: ${{ upper(variables.azure_region) }}
      company: ${{ upper(variables.company) }}
      serviceConn: ${{ variables.devServiceConn }}